project: MLP_reproduction_with_Bayesian_sweeping
program: train.py
method: bayes
metric:
  name: test_roc
  goal: maximize
parameters:
  lr:
    values: [0.01, 0.001, 0.005]
  dropout:
    values: [0, 0.2, 0.4]
  weight-decay:
    values: [0, 0.001]
  act:
    values: ["relu", "None"]
  bias:
    values: [1, 0]